### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by aehyvari**
This PR suggests how to organise the building of the custom docker images of the group that we use currently to speed-up builds in circleci.

The idea is to build and push the docker images to dockerhub at every commit.

Group's dockerhub password is passed in the `verify-docker` context's `VERIFY_DOCKERHUB_PW` environment variable.

I also plan to set up a scheduled workflow for the repository that will build and push the docker images monthly, following CircleCI's schedule for updating the image `cimg/base:current` used by one of the images.

### CODE REVIEW

**Review by blishko — COMMENTED** [review]
I very much support this idea, but I am not sure if this is the right place for this.
This should not run on every commit on every branch, no?

My impression is that we want to push new version to Docker only once changes are accepter to master (and master branch is updated).
It seems like that should be some kind of workflow triggered by an update in master, rather than a CI script that checks if a PR is correct.

Do I understand this workflow correctly?

**Comment by aehyvari** [comment]
Yes, I also think that this is the workflow.  There probably is a way of doing what you describe in circleci, but I don't want to use more time on this...  It'd be great if somebody wants to take it over from here :)

At the same time I think that having this mechanism, even imperfectly implemented, is critical for the sustainability of the setup, especially in combination with the monthly build that synchronise with circleci's understanding of a recent linux installation.  I'd rather have in place a system that might break than not having anything.

**Comment by blishko** [comment]
Yes, I agree that we need a mechanism that will update the images on regular basis to match the updates in the underlying CircleCI images.

In my mind, this would be a GitHub action that triggers on monthly basis and also on every update to master.

But I understand the time constraints :) We can go with this setup for now and I will try to look into this in a near future.
Unless @MasoudAsadzade  or @BritikovKI have some ideas right now :)

**Comment by aehyvari** [comment]
Great, I think we understand each other on this :)

I've now set up the monthly schedule after verifying that my test schedule worked out.

**Review by blishko — APPROVED** [review]
LGTM!

**Pull request merged**
